// Home.js
import React from 'react';

const Home = () => {
  return (
    <div className="container">
      <h2>Home Page</h2>
      <div className="page-content">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt id aliquet risus feugiat in ante metus. Et egestas quis ipsum suspendisse. Nulla aliquet enim tortor at auctor urna nunc. Gravida rutrum quisque non tellus orci ac auctor augue mauris. Egestas maecenas pharetra convallis posuere morbi. Tellus molestie nunc non blandit. Neque aliquam vestibulum morbi blandit cursus risus at ultrices mi. Sagittis eu volutpat odio facilisis mauris sit amet massa. Senectus et netus et malesuada fames ac turpis. Molestie nunc non blandit massa enim nec dui nunc mattis. Feugiat scelerisque varius morbi enim. Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Sit amet nisl purus in mollis nunc sed id. Libero nunc consequat interdum varius sit. Proin sed libero enim sed faucibus turpis in. Pharetra sit amet aliquam id diam maecenas. Amet consectetur adipiscing elit pellentesque. Nunc mattis enim ut tellus elementum.

Nisi scelerisque eu ultrices vitae auctor eu augue. Viverra justo nec ultrices dui sapien eget mi. Ac felis donec et odio pellentesque diam volutpat commodo sed. Volutpat blandit aliquam etiam erat velit. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Sagittis nisl rhoncus mattis rhoncus urna neque. Sed faucibus turpis in eu mi bibendum neque. Blandit massa enim nec dui. Porta non pulvinar neque laoreet suspendisse interdum. Libero volutpat sed cras ornare arcu dui vivamus.

Purus sit amet luctus venenatis lectus magna fringilla. Donec et odio pellentesque diam volutpat. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere morbi. Feugiat in fermentum posuere urna nec tincidunt praesent semper feugiat. Quisque id diam vel quam elementum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Laoreet id donec ultrices tincidunt arcu non sodales neque. Nisi est sit amet facilisis magna etiam tempor. A lacus vestibulum sed arcu non odio euismod. Semper feugiat nibh sed pulvinar proin gravida hendrerit. Elementum nibh tellus molestie nunc non blandit massa enim nec. Lobortis mattis aliquam faucibus purus. In hac habitasse platea dictumst. Iaculis eu non diam phasellus vestibulum lorem. Dictum at tempor commodo ullamcorper. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Turpis tincidunt id aliquet risus. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Auctor augue mauris augue neque gravida.

Posuere ac ut consequat semper. Egestas sed sed risus pretium quam. Nunc non blandit massa enim nec dui. Faucibus pulvinar elementum integer enim. Augue eget arcu dictum varius duis at consectetur lorem. Cras tincidunt lobortis feugiat vivamus at augue. Blandit cursus risus at ultrices. Imperdiet sed euismod nisi porta lorem. Nulla malesuada pellentesque elit eget gravida cum. Neque ornare aenean euismod elementum nisi. Justo eget magna fermentum iaculis eu non diam phasellus vestibulum. Turpis egestas integer eget aliquet. Accumsan lacus vel facilisis volutpat est velit egestas. In fermentum posuere urna nec. Ac placerat vestibulum lectus mauris ultrices eros in. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt.

Pretium quam vulputate dignissim suspendisse in est ante in nibh. Felis imperdiet proin fermentum leo vel orci porta non pulvinar. Semper feugiat nibh sed pulvinar proin gravida hendrerit. Amet massa vitae tortor condimentum lacinia quis vel eros. Id eu nisl nunc mi. Pharetra vel turpis nunc eget lorem dolor sed. Ac ut consequat semper viverra nam libero justo laoreet sit. Aenean euismod elementum nisi quis. Blandit aliquam etiam erat velit scelerisque in. Adipiscing enim eu turpis egestas pretium aenean pharetra. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Eget nunc lobortis mattis aliquam. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Eu nisl nunc mi ipsum. Et malesuada fames ac turpis. Magna etiam tempor orci eu lobortis elementum nibh. Egestas integer eget aliquet nibh praesent tristique magna. Eget felis eget nunc lobortis mattis aliquam faucibus.

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt id aliquet risus feugiat in ante metus. Et egestas quis ipsum suspendisse. Nulla aliquet enim tortor at auctor urna nunc. Gravida rutrum quisque non tellus orci ac auctor augue mauris. Egestas maecenas pharetra convallis posuere morbi. Tellus molestie nunc non blandit. Neque aliquam vestibulum morbi blandit cursus risus at ultrices mi. Sagittis eu volutpat odio facilisis mauris sit amet massa. Senectus et netus et malesuada fames ac turpis. Molestie nunc non blandit massa enim nec dui nunc mattis. Feugiat scelerisque varius morbi enim. Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Sit amet nisl purus in mollis nunc sed id. Libero nunc consequat interdum varius sit. Proin sed libero enim sed faucibus turpis in. Pharetra sit amet aliquam id diam maecenas. Amet consectetur adipiscing elit pellentesque. Nunc mattis enim ut tellus elementum.

Nisi scelerisque eu ultrices vitae auctor eu augue. Viverra justo nec ultrices dui sapien eget mi. Ac felis donec et odio pellentesque diam volutpat commodo sed. Volutpat blandit aliquam etiam erat velit. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Sagittis nisl rhoncus mattis rhoncus urna neque. Sed faucibus turpis in eu mi bibendum neque. Blandit massa enim nec dui. Porta non pulvinar neque laoreet suspendisse interdum. Libero volutpat sed cras ornare arcu dui vivamus.

Purus sit amet luctus venenatis lectus magna fringilla. Donec et odio pellentesque diam volutpat. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere morbi. Feugiat in fermentum posuere urna nec tincidunt praesent semper feugiat. Quisque id diam vel quam elementum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Laoreet id donec ultrices tincidunt arcu non sodales neque. Nisi est sit amet facilisis magna etiam tempor. A lacus vestibulum sed arcu non odio euismod. Semper feugiat nibh sed pulvinar proin gravida hendrerit. Elementum nibh tellus molestie nunc non blandit massa enim nec. Lobortis mattis aliquam faucibus purus. In hac habitasse platea dictumst. Iaculis eu non diam phasellus vestibulum lorem. Dictum at tempor commodo ullamcorper. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Turpis tincidunt id aliquet risus. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Auctor augue mauris augue neque gravida.

Posuere ac ut consequat semper. Egestas sed sed risus pretium quam. Nunc non blandit massa enim nec dui. Faucibus pulvinar elementum integer enim. Augue eget arcu dictum varius duis at consectetur lorem. Cras tincidunt lobortis feugiat vivamus at augue. Blandit cursus risus at ultrices. Imperdiet sed euismod nisi porta lorem. Nulla malesuada pellentesque elit eget gravida cum. Neque ornare aenean euismod elementum nisi. Justo eget magna fermentum iaculis eu non diam phasellus vestibulum. Turpis egestas integer eget aliquet. Accumsan lacus vel facilisis volutpat est velit egestas. In fermentum posuere urna nec. Ac placerat vestibulum lectus mauris ultrices eros in. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt.

Pretium quam vulputate dignissim suspendisse in est ante in nibh. Felis imperdiet proin fermentum leo vel orci porta non pulvinar. Semper feugiat nibh sed pulvinar proin gravida hendrerit. Amet massa vitae tortor condimentum lacinia quis vel eros. Id eu nisl nunc mi. Pharetra vel turpis nunc eget lorem dolor sed. Ac ut consequat semper viverra nam libero justo laoreet sit. Aenean euismod elementum nisi quis. Blandit aliquam etiam erat velit scelerisque in. Adipiscing enim eu turpis egestas pretium aenean pharetra. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Eget nunc lobortis mattis aliquam. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Eu nisl nunc mi ipsum. Et malesuada fames ac turpis. Magna etiam tempor orci eu lobortis elementum nibh. Egestas integer eget aliquet nibh praesent tristique magna. Eget felis eget nunc lobortis mattis aliquam faucibus.
    </div>
    </div>
  );
};

export default Home;
